# Load the brewfile with DJ-wide dependencies
instance_eval(File.read(File.expand_path("~/.config/homebrew/common.Brewfile")))


# Run your GitHub Actions locally
brew "act"
# Static checker for GitHub Actions workflow files
brew "actionlint"
# Improved shell history for zsh, bash, fish and nushell
brew "atuin"
# Statistics utility to count lines of code
brew "cloc"
# Dotfile manager and templater written in rust
brew "dotter"
# Diff tool for YAML files, and sometimes JSON
brew "dyff"
# FAST Kubernetes manifests validator, with support for Custom Resources!
brew "kubeconform"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Cross-shell prompt for astronauts
brew "starship"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"

# Desktop password and login vault
cask "bitwarden"
# Web browser
cask "firefox"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Keyboard customiser
cask "karabiner-elements"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Tool to reverse the direction of scrolling
cask "scroll-reverser"
# Music streaming service
cask "spotify"
# To-do list and time tracker
cask "super-productivity"
# Unicode keyboard layout editor
cask "ukelele"

# very much local only tool, to prevent it from removing it
uv "bumpbot"

vscode "eamodio.gitlens"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "openai.chatgpt"
vscode "pixl-garden.bongocat"
vscode "sreetamd.karma"
vscode "wakatime.vscode-wakatime"

