"$schema" = 'https://starship.rs/config-schema.json'

format = """
$kubernetes\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character\
"""

right_format = """
${custom.djctl}\
"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
detect_extensions = []
detect_files = []

[kubernetes]
format = '[$symbol$context \($namespace\)]($style) '
style = "bold underline red"
symbol = "⛵"
disabled = false
contexts = [
    { context_pattern = "docker-desktop", user_pattern = ".*", style = "green" },
    { context_pattern = "office", style = "bold cyan" },
]

[custom.djctl]
command = "jq -r '.current_context' ${DJCTL_HOME:-~/.dj}/state.json"
style = "purple"
symbol = "🛰️ "
when = "true"
